apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cmp-dev-1
resources:
- db-init-job.yaml
- pg-cluster/cluster.yaml
- app
- pgrest

images:
- name: ghcr.io/samuka007/orm-vs-pgrest-example
  newTag: sha-37d64a9
- name: ghcr.io/samuka007/orm-vs-pgrest-example-migrate
  newTag: sha-37d64a9

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: blog-app
