apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cmp-dev-1

resources:
  - db-init-job.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: ghcr.io/samuka007/orm-vs-pgrest-example-migrate
    newTag: sha-dab3abb

commonLabels:
  app: postgrest
  app.kubernetes.io/component: api
  app.kubernetes.io/part-of: blog-app