apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cmp-dev

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app: postgrest
  app.kubernetes.io/component: api
  app.kubernetes.io/part-of: blog-app