apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-nextjs-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Samuka007/orm-vs-pgrest-example.git
    targetRevision: main
    path: k8s/orm-vs-pgrest/dev
    kustomize:
      namespace: cmp-dev-1
  destination:
    server: https://kubernetes.default.svc
    namespace: cmp-dev-1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true