apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cmp-dev-1

commonAnnotations:
  argocd.argoproj.io/sync-wave: "4"

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

labels:
- includeSelectors: true
  pairs:
    app: nextjs-app
    app.kubernetes.io/component: frontend
