apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cmp-dev-1

resources:
  - db-init-job.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app: nextjs-app
  app.kubernetes.io/component: frontend
  app.kubernetes.io/part-of: blog-app

images:
  - name: ghcr.io/samuka007/orm-vs-pgrest-example
    newTag: sha-dab3abb
  - name: ghcr.io/samuka007/orm-vs-pgrest-example-migrate
    newTag: sha-dab3abb