apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cmp-dev

resources:
  - cluster.yaml

commonLabels:
  app.kubernetes.io/component: database
  app.kubernetes.io/part-of: blog-app